version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: notez-fun-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: notez_fun_db
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - notez-fun-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notez-fun-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://admin:password123@mongodb:27017/notez_fun_db?authSource=admin
      - DB_NAME=notez_fun_db
      - JWT_SECRET_KEY=super-secure-jwt-secret-key-for-development
      - ENVIRONMENT=development
      - CORS_ORIGINS=http://localhost:3000,http://localhost:80
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - notez-fun-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notez-fun-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - REACT_APP_ENVIRONMENT=development
    depends_on:
      - backend
    networks:
      - notez-fun-network

volumes:
  mongodb_data:

networks:
  notez-fun-network:
    driver: bridge