services:
  # Backend Service (FastAPI)
  - type: web
    name: notez-fun-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /api/
    envVars:
      - key: PORT
        value: 8001
      - key: MONGO_URL
        value: "mongodb://notez_admin:your_password@notez-fun-mongodb:27017/notez_fun_db"  # Set MongoDB URL here manually
      - key: DB_NAME
        value: notez_fun_db
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: ENVIRONMENT
        value: production
    
  # Frontend Service (React)
  - type: web
    name: notez-fun-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: notez-fun-backend
          property: host

# Database Configuration
databases:
  - name: notez-fun-mongodb
    databaseName: notez_fun_db
    user: notez_admin
    plan: starter
    region: oregon
    ipAllowList: []

# Additional Configuration
settings:
  buildFilter:
    paths:
      - backend/**
      - frontend/**
    ignoredPaths:
      - "**/*.md"
      - docs/**
